name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Change to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

    - name: Run deployment script on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@3.85.231.35 "bash /home/ec2-user/test/deploy_project.sh"
